FROM rust:1.56
RUN apt update
RUN apt -y upgrade

# Install cross compilation tools
RUN rustup target add x86_64-pc-windows-gnu
RUN apt -y install mingw-w64

# Install rust-analizer
RUN rustup component add rust-src
RUN rustup component add rustfmt
RUN curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz -o /usr/bin/rust-analyzer.gz
RUN gzip -d /usr/bin/rust-analyzer.gz   
RUN chmod 755 /usr/bin/rust-analyzer

RUN apt -y install g++ pkg-config